# Generated by Django 5.1.2 on 2024-11-04 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_options_account_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+254712345678', '0712345678', or '0112345678'.", regex='^\\+2547\\d{8}$|^07\\d{8}$|^01\\d{8}$')]),
        ),
    ]
